= Admonition Styles
:navtitle: Admonitions
:stem: latexmath

An xref:asciidoc/admonitions.adoc[admonition], also known as a notice, helps draw attention to content with a special label or icon.

== Admonition blocks

An admonition block is a table.
The table title element is specified by the block class: tip, note, important, warning, or caution.
Here's an AsciiDoc source example that produces an admonition with the table title warning:

[source,asciidoc]
----
WARNING: Watch out!
----

If font-based icons are enabled (`icons=font`), the table title text is replaced by the associated icon.

[source,html]
----
<div class="admonitionblock warning">
<table>
<tr>
<td class="icon">
<i class="fa icon-warning" title="Warning"></i>
</td>
<td class="content">
<div class="paragraph">
<p>Watch out!</p>
</div>
</td>
</tr>
</table>
</div>
----

Here's how it might appear when the title is displayed as text:

WARNING: Watch out!

== Mathematical blocks

When writing mathematical documents you can use the following style labels:

[horizontal]
Problem statement:: `prob`
Exercise:: `exer`
Example:: `examp`
Lemma:: `lem`
Definition:: `def`
Proof:: `proof`
Proposal:: `prop`
Theorem:: `thm`

Please note that `:stem: latexmath` is defined as a document attribute to render STEM block (using MathJax).

.Problem admonition syntax
[source,adoc]
----
.Problème : Formulation forte du Laplacien
[.prob#prob:1]
****
On cherche stem:[u] telle que
[[eq:64]]
[stem]
++++
    \begin{split}
      -\Delta u &= f \mbox{ dans } \Omega\\
      u &= 0 \mbox{ sur } \partial \Omega
\end{split}
++++
****
----

Here's the result:

.Problème : Formulation forte du Laplacien
[.prob#prob:1]
****
On cherche stem:[u] telle que
[[eq:64]]
[stem]
++++
    \begin{split}
      -\Delta u &= f \mbox{ dans } \Omega\\
      u &= 0 \mbox{ sur } \partial \Omega
\end{split}
++++
****

.Lemma admonition syntax
[source,adoc]
----
.Lemma
[.lem#lem:1]
****
Soit stem:[\Omega] un ouvert borné de stem:[\R{d}].
Il existe une constante stem:[c_\Omega] (dépendente de stem:[\Omega] telle que
[stem]
++++
    \forall v \in H^1_0(\Omega),\quad \|v\|_{0,\Omega} \le c_\Omega \|\nabla v\|_{0,\Omega}
++++
****
----

Here's the result:

.Lemma
[.lem#lem:1]
****
Soit stem:[\Omega] un ouvert borné de stem:[\R{d}].
Il existe une constante stem:[c_\Omega] (dépendente de stem:[\Omega] telle que
[stem]
++++
    \forall v \in H^1_0(\Omega),\quad \|v\|_{0,\Omega} \le c_\Omega \|\nabla v\|_{0,\Omega}
++++
****

.Exercise admonition syntax
[source,adoc]
----
.Exercise: Find the magic number
[.exer#exer:1]
****
This is an exercise...
****
----

Here's the result:

.Exercise: Find the magic number
[.exer#exer:1]
****
This is an exercise...
****

.Example admonition syntax
[source,adoc]
----
.Example: Théorème de Lax-Milgram
[.examp#examp:1]
****
This is an example.
****
----

Here's the result:

.Example: Théorème de Lax-Milgram
[.examp#examp:1]
****
This is an example.
****

.Theorem admonition syntax
[source,adoc]
----
.Theorem de Perlimpinpin
[.thm#thm:1]
****
Soit stem:[V] un espace de Hilbert et stem:[a \in \mathcal{L}(V \times V, \RR)] une forme bilinéaire continue et _coercive_ sur stem:[V]. Alors, pour toute forme linéaire continue stem:[\ell \in \mathcal{L}(V, \RR)], le problème est bien posé
****
----

Here's the result:

.Theorem de Perlimpinpin
[.thm#thm:1]
****
Soit stem:[V] un espace de Hilbert et stem:[a \in \mathcal{L}(V \times V, \RR)] une forme bilinéaire continue et _coercive_ sur stem:[V]. Alors, pour toute forme linéaire continue stem:[\ell \in \mathcal{L}(V, \RR)], le problème est bien posé
****

.Corollaire admonition syntax
[source,adoc]
----
.Corollaire de toto
[.cor#cor:1]
****
Soit stem:[V] un espace de Hilbert et stem:[a \in \mathcal{L}(V \times V, \RR)] une forme bilinéaire continue et _coercive_ sur stem:[V]. Alors, pour toute forme linéaire continue stem:[\ell \in \mathcal{L}(V, \RR)], le problème est bien posé
****
----

Here's the result:

.Corollary de toto
[.cor#cor:1]
****
Soit stem:[V] un espace de Hilbert et stem:[a \in \mathcal{L}(V \times V, \RR)] une forme bilinéaire continue et _coercive_ sur stem:[V]. Alors, pour toute forme linéaire continue stem:[\ell \in \mathcal{L}(V, \RR)], le problème est bien posé
****

.Definition admonition syntax
[source,adoc]
----
.Definition de Perlimpinpin
[.def#def:1]
****
Une forme bilinéaire stem:[a \in \mathcal{L}(V \times V, \RR)] est _coercive_ sur stem:[V] s’il existe une constante stem:[\alpha > 0].
****
----

Here's the result:

.Definition de Perlimpinpin
[.def#def:1]
****
Une forme bilinéaire stem:[a \in \mathcal{L}(V \times V, \RR)] est _coercive_ sur stem:[V] s’il existe une constante stem:[\alpha > 0].
****

.Proposal admonition syntax
[source,adoc]
----
.Proposition
[.prop#prop:7]
****
La forme bilinéaire stem:[a] du problème <<prob:2>> est _coercive_
****
----

Here's the result:

.Proposition
[.prop#prop:7]
****
La forme bilinéaire stem:[a] du problème <<prob:2>> est _coercive_
****

.Proof admonition syntax
[source,adoc]
----
.Preuve
[%collapsible.proof]
====
On note tout d’abord que par l’inégalité de Poincaré et la définition de
stem:[\|\cdot\|_{1,\Omega}]
[[eq:68]]
[stem]
++++
      \|v\|^2_{1,\Omega} \le (1 + c^2_\Omega) \|\nabla v\|^2_{0,\Omega}
++++
On en déduit que
[[eq:67]]
[stem]
++++
\forall v \in H^1_0(\Omega),\quad a(v,v) = \|\nabla v\|^2_{0,\Omega} \ge \frac{1}{1+c^2_\Omega} \|v\|^2_{1,\Omega}
++++

Le Lemme de Lax-Milgram permet alors de conclure sur l’existence d’une solution unique pour le problème <<prob:2>>.
====
----

Here's the result:

.Preuve
[%collapsible.proof]
====
On note tout d’abord que par l’inégalité de Poincaré et la définition de
stem:[\|\cdot\|_{1,\Omega}]
[[eq:68]]
[stem]
++++
      \|v\|^2_{1,\Omega} \le (1 + c^2_\Omega) \|\nabla v\|^2_{0,\Omega}
++++
On en déduit que
[[eq:67]]
[stem]
++++
\forall v \in H^1_0(\Omega),\quad a(v,v) = \|\nabla v\|^2_{0,\Omega} \ge \frac{1}{1+c^2_\Omega} \|v\|^2_{1,\Omega}
++++

Le Lemme de Lax-Milgram permet alors de conclure sur l’existence d’une solution unique pour le problème <<prob:2>>.
====

NOTE: The `collapsible` option is used to make the block content collapsible (i.e., revealed or hidden on interaction).
By default, the block content is hidden. You can use the `%open` option to make it visible.
